# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY app/ ./app/
COPY requirements.txt setup.py pyproject.toml ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port Flask will run on
EXPOSE 5000

# Run the Flask app
CMD ["python", "app/app.py"]
