image:
  repository: gcr.io/coherent-window-464903-b1/flask-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
