image:
  repository: gcr.io/helm-final/flask-app
  tag: v1
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 5050

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

resources: {}
